### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by SourcingDenis** [strawp/LinkedInBuddy#1]
Hello, @strawp am super interested in learning more about how to use your tool as I am a non-programming person :( Is that something that I am capable of handling? Many thanks for your time. Cheers, Denis

**Comment by strawp** [comment]
It requires Burp Suite Pro: https://portswigger.net/burp

You can then load this as an extension into Burp Extender.

**Comment by Space-Cased** [comment]
I had almost a verbatim message from SourcingDenis on my github account. IHe is asking us all a simple question, something along the lines on if we can explain how it works. . I am just not quite sure if he is legitimately concerned with the answer.  My question, is there anything he has to gain in our answer besides its content?

**Comment by SourcingDenis** [comment]
dude, don't overthink it! cheers, Denis
